In [2]:
import numpy as np
import tensorflow as tf
from tensorflow import keras
from tensorflow.keras import Sequential
from tensorflow.keras.layers import LSTM, Dense

In [3]:
data = np.array([10,20,30,40,50,60,70,80,90,100], dtype=float)

data = data / 100

In [4]:
X = []
y = []

for i in range(len(data) - 3):
    X.append(data[i:i+3])
    y.append(data[i+3])

X = np.array(X)
y = np.array(y)

In [5]:
X

array([[0.1, 0.2, 0.3],
       [0.2, 0.3, 0.4],
       [0.3, 0.4, 0.5],
       [0.4, 0.5, 0.6],
       [0.5, 0.6, 0.7],
       [0.6, 0.7, 0.8],
       [0.7, 0.8, 0.9]])

In [6]:
y

array([0.4, 0.5, 0.6, 0.7, 0.8, 0.9, 1. ])

In [7]:
X = X.reshape((X.shape[0], X.shape[1], 1))

In [8]:
X

array([[[0.1],
        [0.2],
        [0.3]],

       [[0.2],
        [0.3],
        [0.4]],

       [[0.3],
        [0.4],
        [0.5]],

       [[0.4],
        [0.5],
        [0.6]],

       [[0.5],
        [0.6],
        [0.7]],

       [[0.6],
        [0.7],
        [0.8]],

       [[0.7],
        [0.8],
        [0.9]]])

In [9]:
X.shape

(7, 3, 1)

In [10]:
model = Sequential()

model.add(LSTM(32, input_shape=(3, 1)))
model.add(Dense(1))

model.compile(optimizer='adam',loss='mse')

model.summary()

D:\Users\HP\anaconda3\envs\dl\Lib\site-packages\keras\src\layers\rnn\rnn.py:199: UserWarning: Do not pass an `input_shape`/`input_dim` argument to a layer. When using Sequential models, prefer using an `Input(shape)` object as the first layer in the model instead.
  super().__init__(**kwargs)


Model: "sequential"

┏━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━━━┓
┃ Layer (type)                         ┃ Output Shape                ┃         Param # ┃
┡━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━━━┩
│ lstm (LSTM)                          │ (None, 32)                  │           4,352 │
├──────────────────────────────────────┼─────────────────────────────┼─────────────────┤
│ dense (Dense)                        │ (None, 1)                   │              33 │
└──────────────────────────────────────┴─────────────────────────────┴─────────────────┘

 Total params: 4,385 (17.13 KB)

 Trainable params: 4,385 (17.13 KB)

 Non-trainable params: 0 (0.00 B)

In [ ]:
history = model.fit(X,y,epochs=1000)

Epoch 1/1000
1/1 ━━━━━━━━━━━━━━━━━━━━ 3s 3s/step - loss: 0.4019
Epoch 2/1000
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 88ms/step - loss: 0.3878
Epoch 3/1000
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 67ms/step - loss: 0.3739
Epoch 4/1000
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 92ms/step - loss: 0.3602
Epoch 5/1000
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 88ms/step - loss: 0.3468
Epoch 6/1000
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 177ms/step - loss: 0.3336
Epoch 7/1000
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 182ms/step - loss: 0.3207
Epoch 8/1000
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 105ms/step - loss: 0.3080
Epoch 9/1000
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 163ms/step - loss: 0.2956
Epoch 10/1000
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 183ms/step - loss: 0.2834
Epoch 11/1000
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 97ms/step - loss: 0.2714
Epoch 12/1000
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 91ms/step - loss: 0.2597
Epoch 13/1000
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 103ms/step - loss: 0.2482
Epoch 14/1000
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 99ms/step - loss: 0.2369
Epoch 15/1000
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 171ms/step - loss: 0.2259

In [ ]:
import matplotlib.pyplot as plt

plt.plot(history.history['loss'])
plt.xlabel('Epoch')
plt.ylabel('Loss')
plt.show()

In [ ]:
test = np.array([80, 90, 100])

test=test/100

test = test.reshape(1, 3, 1)

print(100*model.predict(test))

In [ ]:
test = np.array([50, 60, 70])

test=test/100

test = test.reshape(1, 3, 1)

print(100*model.predict(test))
